import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../components/header';
import Footer from '../components/footer';
import PageTransitionLoader from '../components/PageTransitionLoader';

const geistInter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TinyCheque',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo/Tinychequelogo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistInter.variable} antialiased scroll-smooth `}>
        <PageTransitionLoader>
          <Header /> {children} <Footer />
        </PageTransitionLoader>
      </body>
    </html>
  );
}
